apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturermanufactureribft
  namespace: manufacturer-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturermanufactureribft
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-besu/charts/node_besu
  values:
    metadata:
      namespace: manufacturer-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://79c5f87f4b0488254ede5c5738b59057f6e5c5d713e2db2d7c9a2174878d0b9d34dbe0c39ec281088fc1920ea146be9963ac4c38d75e57b48dfeaac5cd23afc1@validator1.supplychain-bes:15010"
      - "enode://5805b888d307c98e9e8c8815cf9df083bd74bcaac156e035aa589127196d737e708330a65388136bf06a2533bc5b257b700814de4252d84458c6e4b40173a47d@validator2.supplychain-bes:15012"
      - "enode://3df72005e0fbce22b5f693980d070b81a9fd81067619ab69a54fe53c2a9e83b822262bcaf4ffd091dc35853d05c925d856cb1eb6d2a961e44832a0b6bd8dedcf@validator3.supplychain-bes:15014"
      - "enode://29093d45bfb7efae6ee4b956597bec6a9188c589b71461167321198f31db3c93e6450cd924a1c20f3cacdf941489a3e79f8fabab9ba247bcdf61a3e4b87b557a@validator4.supplychain-bes:15016"
      - "enode://1ff88eb2e9ef8c896561741f5f6ef2b24e2a8cf532b2afebefafe63bdd8ef6664d460b1ddbaa78cdc08b455d152387f74d0770d611b8fd5ce99b76ce74825f52@carrier.carrier-bes:15020"
      - "enode://ff513bb34205ee43ea541774aa101ad62ea1e8ef906457cabba2fc96ff3333800d826fa9000ec2bd0606b94a31abcac817f3cfbc631a712513fb502cf33e15e3@manufacturer.manufacturer-bes:15030"
   

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    proxy:
      provider: none
      external_url: manufacturer.manufacturer-bes
      p2p: 15030
      rpc: 15031      

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0     

    node:
      name: manufacturer
      consensus: ibft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      
      url: "https://manufacturer-tessera.manufacturer-bes:8888"
      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/manufacturer-bes/crypto/manufacturer
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besumanufacturer

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDBhN2QxZTYyNDNkYTMwOGVmZTQzZjM1MTdhNDQxZGI0N2NlYTc4NTI5NDY2NzlhMGE4ZDc1MjllYjQ3OTAyYzc5N2UyN2JmM2ZkZjgwYjY3Nzk5NDU4ZDUzM2I2MjlhMThiNjEyYmRlM2M1MTBmNzJlNWExNzcyMjU4NTQ5NGVjZTFjNzlmOTNmMDA5YTEyMGVlY2ZhMDgxMDQ2Njc5Yjk2MGM5NWM4MDg0MDAwMDAwMDBjMCIKfQ==
