apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: signer
  annotations:
    fluxcd.io/automated: "false"
  namespace: cenm-ent
spec:
  releaseName: signer
  chart:
    path: platforms/r3-corda-ent/charts/signer
    git: https://github.com/suvajit-sarkar/blockchain-automation-framework.git
    ref: develop
  values:
    nodeName: signer
    metadata:
      namespace: cenm-ent
    image:
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      signerContainerName: corda/enterprise-signer:1.2-zulu-openjdk8u242
      imagePullSecret: regcred
      pullPolicy: Always
    acceptLicense: YES
    vault:
      address: http://172.17.0.2:8200
      role: vault-role
      authPath: cordaentcenm
      serviceAccountName: vault-auth
      certSecretPrefix: secret/cenm
      retries: 10
      sleepTimeAfterError: 15
    service:
      ssh:
        port: 2222
        targetPort: 2222
        type: ClusterIP
      shell:
        user: signer
        password: signerP
    serviceLocations:
      identityManager:
        host: idman.cenm-ent
        publicIp: idman.cenm-ent
        port: 5052
        publicPort: 8443
      networkMap:
        host: networkmap.cenm-ent
        port: 5050
      revocation:
        port: 5053
    signers:
      CSR:
        schedule:
          interval: 1m
      CRL:
        schedule:
          interval: 1d
      NetworkMap:
        schedule:
          interval: 1m
      NetworkParameters:
        schedule:
          interval: 1m
    config:
      volume:
        baseDir: /opt/corda
      jarPath: bin
      configPath: etc
      cordaJar:
        memorySize: 512
        unit: M
      pod:  
        resources:
          limits: 512M
          requests: 512M
      replicas: 1
