apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb-networkmap
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ns
spec:
  replicaCount: 1
  replicas: 1
  releaseName: mongodb-networkmap
  chart:
    path: platforms/r3-corda/charts/mongodb
    git: https://github.com/suvajit-sarkar/blockchain-automation-framework.git
    ref: develop
  values:
    nodeName: mongodb-networkmap
    metadata:
      namespace: supplychain-ns
    image:
      containerName: mongo:3.6.6
      imagePullSecret: regcred
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      memory: 512Mi
      name: minikubestorageclass
      mountPath: /data/db
      volname: hostvol
    vault:
      address: http://172.17.0.3:8200
      role: vault-role
      authpath: cordanetworkmap
      secretprefix: networkmap/credentials/mongodb
      serviceaccountname: vault-auth
      certsecretprefix: networkmap/certs
    service:
      tcp:
          port: 27017
          targetPort: 27017
      type: NodePort
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    mongodb:
      username: networkmap
    cluster:
      enabled: false