apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrierdb
  annotations:
    fluxcd.io/automated: "false"
  namespace: carrier-ns
spec:
  releaseName: carrierdb
  chart:
    path: platforms/r3-corda/charts/h2
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: workspace
  values:
    replicaCount: 1
    nodeName: carrier
    metadata:
      namespace: carrier-ns
    image:
      containerName: index.docker.io/hyperledgerlabs/h2:2018
      imagePullSecret: regcred
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      memory: 512Mi
      mountPath: "/opt/h2-data"
      name: awsstorageclass
    service:
      type: NodePort
      p2p:
        port: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005
      tcp:
        port: 9101
        targetPort: 1521
      web:
        targetPort: 81
        port: 8080
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}