apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainvalidator2ibft
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator2ibft
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://122fa30c07233522414a4baf5fedeadb865d68495553c3247bc9eb7c486755af0c3dd6b5f9b0d5883b210db98d972f04c68c8e030772aa583f5c406dc4432d51@validator1.supplychain-bes:30303"
      
      - "enode://76bcebd7150f0d88fdb72dc2cdc4bfb4ce8f40c3d37324b6c1125e235e33c18e390beb85a1cea5c6a9151bf8728d6d3a94e7e9606d971b96977b2a125bfb7a63@validator2.supplychain-bes:30303"
      
      - "enode://4907f4d596e9d94a40e9cc32bebd821369e4b640e7cafaceed6a125689e680a687bec4cc4dd009b03405c72ce5faf07970f0d4e9712a488d586524f967ad764e@validator3.supplychain-bes:30303"
      
      - "enode://c06c586cff2db02c689e32fc4869635c23adfc7273f4d280a62541da233bb10dd85552a6436099c44348100c186b9a3bac5d4e9f1061fc464c881877c9aafad8@validator4.supplychain-bes:30303"
      
      - "enode://0a1c2b90e88806e1dcbff922c71ae6437ccf2565a7fedca8d3424c85e6cbdd5cce2681bacf0d8169a2df6bb91a7659df33766968c905d132c4cd0f737ebb4fc7@carrier.carrier-bes:30303"
      
      - "enode://d8b48fa3cfa560ed1ae583d9a70cd854630262168e47a37d89b42b01bbed5887afb4d8426e2665bed090e5d126e9df126ec50b716ecaa912699b53b8d8d216fd@manufacturer.manufacturer-bes:30303"
      

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: supplychain-bes

    liveliness_check:
      enabled: false

    proxy:
      provider: none
      external_url: supplychain.supplychain-bes
      p2p: 15012
      rpc: 15013

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/supplychain-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDk1N2NmMzlkYzhkMjMzMGQ4YjZjYWI4MmU2ZTdkNDcyZmYxMmMwM2Y5NDg2NGJhZmQ1NGFlMDU3ZmYyNDgzYTI1ZDhjYWY3NmI1MWZhNmIxNTM5NDg0Y2Y2OGQ1YWVjMjZiNzFmY2FlZWIyZTMwNWUxODdmNmRjNjZiOGM5NDk2MmI2YzU1NzcyNjU1MzAyODExMGJkOGUzODNjNDZjOTE0MzJhODI4MDg0MDAwMDAwMDBjMCIKfQ==
