apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-net-ca
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-net-ca
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: supplychain-net
      images:
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplychain-admin
    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: demo-fabricsupplychain-net-auth
      secretcert: secret/crypto/ordererOrganizations/supplychain-net/ca?ca.supplychain-net-cert.pem
      secretkey: secret/crypto/ordererOrganizations/supplychain-net/ca?supplychain-net-CA.key
      secretadminpass: secret/credentials/supplychain-net/ca/supplychain?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: orderer
      external_url_suffix: hf.demo.aws.blockchaincloudpoc.com
