# This is custom git Action created to run molecule test cases during any push on develop branch
# The workflow is divided into test stages, based on the PR title particular test stages will run
# The test coverage is for BAF corda and fabric. Other DLTs will be added gradually

name: Molecule Test Workflow

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install molecule==3.0.6 yamllint ansible-lint docker==4.2.2 openshift
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if: |
        contains(github.event.pull_request.title, '[shared]') ||
        contains(github.event.pull_request.title, '[corda]') ||
        contains(github.event.pull_request.title, '[fabric]')
    - name: Test Stage Shared default
      run: |
        cd ./platforms/shared/configuration
        # export the bin path 
        export PATH=~/bin:$PATH
        printenv
        molecule test -s default
      if: contains(github.event.pull_request.title, '[shared]')
    - name: Test Stage kubernetes-corda
      run: |
        cd ./platforms/shared/configuration
        molecule test -s kubernetes-corda
      if: contains(github.event.pull_request.title, '[shared]')
    - name: Test Stage kubernetes-fabric
      run: |
        cd ./platforms/shared/configuration
        molecule test -s kubernetes-fabric
      if: contains(github.event.pull_request.title, '[shared]')
    
    # Below tests needs to be fixed in molecule tests before makeing this active 
    - name: Test Stage Fabric default
      run: | 
        cd ./platforms/hyperledger-fabric/configuration
        molecule test -s default
      if: contains(github.event.pull_request.title, '[_fabric]')
    - name: Test Stage Fabric default
      run: | 
        cd ./platforms/hyperledger-fabric/configuration
        molecule test -s default
      if: contains(github.event.pull_request.title, '[_fabric]')
    - name: Test Stage Fabric crypto
      run: | 
        cd ./platforms/hyperledger-fabric/configuration
        molecule test -s crypto
      if: contains(github.event.pull_request.title, '[_fabric]')
    - name: Test Stage Corda default
      run: | 
        cd ./platforms/r3-corda/configuration
        molecule test -s default
      if: contains(github.event.pull_request.title, '[_corda]')
